#
# WARNING: DO NOT ADD CUSTOM BUILD COMMANDS TO THIS FILE.
#   This makefile is only provided as a courtesy shortcut for Linux users.
#		Using other toolchains, it is not used at all, so any additional custom
#   commands will not be executed, breaking those builds.
#

nope.pdf: IEEEtran.cls nope.tex
	pdflatex nope.tex

clean:
	rm -f nope.aux nope.out nope.fdb_latexmk nope.fls nope.log nope.synctex.gz
